#Basic workflow to deploy our boilerplate project

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTIP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/a3-bulldoguk-boilerplate
          export APOS_RELEASE_ID=boilerplate2021
          git pull https://github.com/bulldoguk/a3-bulldoguk-boilerplate.git main
          npm install
          npm run build
          pm2 start
          pm2 save